{
 "title": "Business Engine",
 "description": "node.js prometheus client basic metrics",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "instance",
    "label": "instance",
    "query": "label_values(nodejs_version_info, instance)"
   },
   {
    "name": "alert",
    "label": "Alert",
    "query": {
     "query": "label_values(alert_execution_duration_seconds_sum,alert)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Alert Results",
   "type": "barchart",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "max (alert_execution_duration_seconds_count{alert=~\"$alert\"}) by(state, alert)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Alert Latency",
   "type": "barchart",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "((rate(alert_execution_duration_seconds_sum{instance=~\"$instance\", alert=~\"$alert\"}[$__rate_interval])\n/\nrate(alert_execution_duration_seconds_count{instance=~\"$instance\", alert=~\"$alert\"}[$__rate_interval])) > 0) != Inf",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Requests", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 12 } },
  {
   "title": "Business Engine API Requests",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 13 },
   "targets": [
    {
     "expr": "rate(http_all_success_total[$__rate_interval])",
     "legendFormat": "Success"
    },
    {
     "expr": "rate(http_all_errors_total[$__rate_interval])",
     "legendFormat": "Errors"
    }
   ]
  },
  {
   "title": "Business Engine Latency",
   "type": "bargauge",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "first" ] } },
   "targets": [
    {
     "expr": "((sum(rate(http_request_duration_seconds_sum{instance=~\"$instance\"}[$__rate_interval])) by (route, method)\n/\nsum(rate(http_request_duration_seconds_count{instance=~\"$instance\"}[$__rate_interval])) by (route, method)) > 0) != Inf",
     "legendFormat": "{{method}} {{route}}"
    }
   ]
  },
  {
   "title": "Grafana API Requests",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 22 },
   "targets": [
    {
     "expr": "rate(grafana_http_request_duration_seconds_count[$__rate_interval])",
     "legendFormat": "{{method}} {{route}} [{{code}}]"
    }
   ]
  },
  {
   "title": "Grafana Latency",
   "type": "bargauge",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "((sum(rate(grafana_http_request_duration_seconds_sum{instance=~\"$instance\"}[$__rate_interval])) by (route, method)\n/\nsum(rate(grafana_http_request_duration_seconds_count{instance=~\"$instance\"}[$__rate_interval])) by (route, method)) > 0 ) != Inf",
     "legendFormat": "{{method}} {{route}}"
    }
   ]
  },
  { "title": "Processes", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 31 } },
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "irate(process_cpu_user_seconds_total{instance=~\"$instance\"}[$__rate_interval]) * 100",
     "legendFormat": "User CPU - {{instance}}"
    },
    {
     "expr": "irate(process_cpu_system_seconds_total{instance=~\"$instance\"}[$__rate_interval]) * 100",
     "legendFormat": "Sys CPU - {{instance}}"
    }
   ]
  },
  {
   "title": "Event Loop Lag",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "nodejs_eventloop_lag_seconds{instance=~\"$instance\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 43 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "process_resident_memory_bytes{instance=~\"$instance\"}",
     "legendFormat": "Process Memory - {{instance}}"
    },
    {
     "expr": "nodejs_heap_size_total_bytes{instance=~\"$instance\"}",
     "legendFormat": "Heap Total - {{instance}}"
    },
    {
     "expr": "nodejs_heap_size_used_bytes{instance=~\"$instance\"}",
     "legendFormat": "Heap Used - {{instance}}"
    },
    {
     "expr": "nodejs_external_memory_bytes{instance=~\"$instance\"}",
     "legendFormat": "External Memory - {{instance}}"
    }
   ]
  },
  {
   "title": "Active Handlers/Requests Total",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 43 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "nodejs_active_handles_total{instance=~\"$instance\"}",
     "legendFormat": "Active Handler - {{instance}}"
    },
    {
     "expr": "nodejs_active_requests_total{instance=~\"$instance\"}",
     "legendFormat": "Active Request - {{instance}}"
    }
   ]
  }
 ]
}