services:
  grafana:
    image: grafana/grafana:11.2.0
    env_file: .env
    ports:
      - 3000:3000
    volumes:
      - ./grafana:/var/lib/grafana
      - ./volkovlabs-manager-app:/var/lib/grafana/plugins/volkovlabs-manager-app
      - ./provisioning:/etc/grafana/provisioning

  database:
    image: timescale/timescaledb:latest-pg14
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
    ports:
      - 5432:5432
    volumes:
      - ./database:/var/lib/postgresql/data

  engine:
    depends_on:
      - database
      - grafana
    image: ghcr.io/volkovlabs/business-engine:2.0.0
    env_file: .env
    ports:
      - 3001:3001
      - 3002:3002

  prometheus:
    image: prom/prometheus:latest
    volumes:
      - ./prometheus/:/etc/prometheus/
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
      - "--storage.tsdb.path=/prometheus"
      - "--web.console.libraries=/usr/share/prometheus/console_libraries"
      - "--web.console.templates=/usr/share/prometheus/consoles"
    ports:
      - 9090:9090

  webhook-json:
    build:
      context: ./webhook-json
    volumes:
      - ./webhook-json/events:/app/events
