services:
  postgres:
    container_name: postgres
    image: postgres
    restart: always
    ports:
      - 5432:5432
    shm_size: 128mb
    environment:
      POSTGRES_PASSWORD: postgres
    volumes:
      - ./postgres:/var/lib/postgresql/data

  engine:
    container_name: engine
    image: ghcr.io/volkovlabs/business-engine:3.6.0
    depends_on:
      - postgres
    ports:
      - 3001:3001
    environment:
      DATABASE_HOST: postgres
      DATABASE_PORT: 5432
      DATABASE_DB: postgres
      DATABASE_USERNAME: postgres
      DATABASE_PASSWORD: postgres

  node-red:
    container_name: node-red
    image: nodered/node-red:latest
    ports:
      - 1880:1880
    volumes:
      - ./node-red/data:/data

  alloy:
    container_name: alloy
    image: grafana/alloy:latest
    ports:
      - 12345:12345
    volumes:
      - ./alloy/config.alloy:/etc/alloy/config.alloy
      - ./alloy/data:/var/lib/alloy/data
      - /var/run/docker.sock:/var/run/docker.sock
    command: run --server.http.listen-addr=0.0.0.0:12345 --storage.path=/var/lib/alloy/data /etc/alloy/config.alloy
