services:
  postgres:
    container_name: postgres
    image: postgres
    restart: always
    ports:
      - 5432:5432
    shm_size: 128mb
    environment:
      POSTGRES_PASSWORD: postgres
    volumes:
      - ./postgres:/var/lib/postgresql/data

  engine:
    container_name: business-engine
    image: ghcr.io/volkovlabs/business-engine:3.4.0
    init: true
    depends_on:
      - postgres
    ports:
      - 3001:3001
    environment:
      DATABASE_HOST: postgres
      DATABASE_PORT: 5432
      DATABASE_DB: postgres
      DATABASE_USERNAME: postgres
      DATABASE_PASSWORD: postgres

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    restart: always
    ports:
      - 9090:9090
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - ./prometheus/data:/prometheus
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
      - "--storage.tsdb.path=/prometheus"
      - "--web.console.libraries=/etc/prometheus/console_libraries"
      - "--web.console.templates=/etc/prometheus/consoles"
      - "--web.enable-lifecycle"

  json-server:
    container_name: json-server
    build:
      context: ./json-server
    volumes:
      - ./json-server/events:/app/events

  node-red:
    container_name: node-red
    image: nodered/node-red:latest
    ports:
      - 1880:1880
    volumes:
      - ./node-red/data:/data
