version: "3.4"

services:
  grafana:
    container_name: grafana
    image: grafana/grafana:10.2.2
    env_file: .env
    ports:
      - 3000:3000
    volumes:
      - ./grafana:/var/lib/grafana
      - ./volkovlabs-bi-app:/var/lib/grafana/plugins/volkovlabs-bi-app
      - ./provisioning:/etc/grafana/provisioning

  database:
    container_name: database
    image: timescale/timescaledb:latest-pg14
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
    ports:
      - 5432:5432
    volumes:
      - ./timescale:/docker-entrypoint-initdb.d
      - ./database:/var/lib/postgresql/data

  engine:
    container_name: engine
    depends_on:
      - database
      - grafana
    image: ghcr.io/volkovlabs/bi-engine:1.4.0
    env_file: .env
    ports:
      - 3001:3001

  webhook-json:
    container_name: webhook-json
    build:
      context: ./webhook-json
    ports:
      - 3002:3000
    volumes:
      - ./webhook-json/events:/app/events

  node-red:
    container_name: node-red
    image: nodered/node-red:latest
    ports:
      - 1880:1880
    volumes:
      - ./node-red:/data

  data-generator:
    container_name: data-generator
    build:
      context: ./timescale
    ports:
      - 3003:3003/tcp
    depends_on:
      - database
    environment:
      WAIT_HOSTS: database:5432
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_HOST: database
