services:
  grafana:
    image: grafana/grafana:11.2.0
    ports:
      - 3000:3000
    volumes:
      - ./provisioning:/etc/grafana/provisioning
    profiles:
      - grafana

  timescale:
    image: timescale/timescaledb:latest-pg14
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
    ports:
      - 5432:5432
    profiles:
      - engine

  engine:
    depends_on:
      - timescale
    image: ghcr.io/volkovlabs/business-engine:2.1.0
    env_file: .env
    ports:
      - 3001:3001
      - 3002:3002
    profiles:
      - engine

  prometheus:
    image: prom/prometheus:latest
    volumes:
      - ./prometheus/:/etc/prometheus/
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
      - "--storage.tsdb.path=/prometheus"
      - "--web.console.libraries=/usr/share/prometheus/console_libraries"
      - "--web.console.templates=/usr/share/prometheus/consoles"
    ports:
      - 9090:9090
    profiles:
      - engine

  json-server:
    build:
      context: ./json-server
    volumes:
      - ./json-server/events:/app/events
    profiles:
      - actions
