services:
  grafana:
    image: grafana/grafana:11.2.0
    environment:
      - GF_USERS_DEFAULT_THEME=light
      - GF_INSTALL_PLUGINS=yesoreyeram-infinity-datasource
    ports:
      - 3000:3000
    volumes:
      - ./provisioning:/etc/grafana/provisioning
    profiles:
      - grafana

  timescale:
    image: timescale/timescaledb:latest-pg14
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
    ports:
      - 5432:5432
    volumes:
      - ./timescale:/docker-entrypoint-initdb.d
    profiles:
      - emulator
      - engine

  data-emulator:
    build:
      context: ./timescale
    depends_on:
      - timescale
    environment:
      WAIT_HOSTS: timescale:5432
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_HOST: timescale
    profiles:
      - emulator

  engine:
    depends_on:
      - timescale
    image: ghcr.io/volkovlabs/business-engine:2.3.0
    #env_file: .env
    environment:
      DATABASE_HOST: timescale
      DATABASE_PORT: 5432
      DATABASE_DB: postgres
      DATABASE_USERNAME: postgres
      DATABASE_PASSWORD: postgres
      GRAFANA_URL: http://grafana:3000
      GRAFANA_TOKEN: SERVICE-ACCOUNT-TOKEN
    ports:
      - 3001:3001
      - 3002:3002
    profiles:
      - engine

  prometheus:
    image: prom/prometheus:latest
    volumes:
      - ./prometheus/:/etc/prometheus/
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
      - "--storage.tsdb.path=/prometheus"
      - "--web.console.libraries=/usr/share/prometheus/console_libraries"
      - "--web.console.templates=/usr/share/prometheus/consoles"
    ports:
      - 9090:9090
    profiles:
      - engine

  json-server:
    build:
      context: ./json-server
    volumes:
      - ./json-server/events:/app/events
    profiles:
      - actions
