global:
  scrape_interval: 15s

scrape_configs:
  - job_name: "business-engine"
    static_configs:
      - targets: ["engine:3001"]
      - targets: ["engine:3002"]
#remote_write:
#  - url: https://prometheus-blocks-prod-us-central1.grafana.net/api/prom/push
#    basic_auth:
#      username: ""
#      password: glc_123==
