{
 "title": "Business Engine",
 "description": "node.js prometheus client basic metrics",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "instance",
    "label": "instance",
    "query": "label_values(nodejs_version_info, instance)"
   },
   { "name": "app", "label": "App", "query": { "query": "label_values(app)" } },
   {
    "name": "alert",
    "label": "Alert",
    "query": {
     "query": "label_values(alert_execution_duration_seconds_sum,alert)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Alert Results",
   "type": "barchart",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "max (alert_execution_duration_seconds_count{alert=~\"$alert\", app=~\"$app\"}) by(state, alert)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Alert Latency",
   "type": "barchart",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "((rate(alert_execution_duration_seconds_sum{instance=~\"$instance\", app=~\"$app\", alert=~\"$alert\"}[$__rate_interval])\n/\nrate(alert_execution_duration_seconds_count{instance=~\"$instance\", app=~\"$app\", alert=~\"$alert\"}[$__rate_interval])) > 0) != Inf",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Requests", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 12 } },
  {
   "title": "Business Engine API Requests",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 13 },
   "targets": [
    {
     "expr": "rate(http_all_success_total{app=~\"$app\",instance=~\"$instance\"}[$__rate_interval])",
     "legendFormat": "{{app}} Success on {{instance}}"
    },
    {
     "expr": "rate(http_all_errors_total{app=~\"$app\",instance=~\"$instance\"}[$__rate_interval])",
     "legendFormat": "{{app}} Errors on {{instance}}"
    }
   ]
  },
  {
   "title": "Business Engine Latency",
   "type": "bargauge",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "first" ] } },
   "targets": [
    {
     "expr": "((sum(rate(http_request_duration_seconds_sum{instance=~\"$instance\", app=~\"$app\"}[$__rate_interval])) by (route, method)\n/\nsum(rate(http_request_duration_seconds_count{instance=~\"$instance\", app=~\"$app\"}[$__rate_interval])) by (route, method)) > 0) != Inf",
     "legendFormat": "{{method}} {{route}}"
    }
   ]
  },
  {
   "title": "Grafana API Requests",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 22 },
   "targets": [
    {
     "expr": "rate(grafana_http_request_duration_seconds_count{app=~\"$app\",instance=~\"$instance\"}[$__rate_interval])",
     "legendFormat": "{{app}} {{method}} {{route}} [{{code}}] on {{instance}}"
    }
   ]
  },
  {
   "title": "Grafana Latency",
   "type": "bargauge",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "((sum(rate(grafana_http_request_duration_seconds_sum{instance=~\"$instance\", app=~\"$app\"}[$__rate_interval])) by (route, method)\n/\nsum(rate(grafana_http_request_duration_seconds_count{instance=~\"$instance\", app=~\"$app\"}[$__rate_interval])) by (route, method)) > 0 ) != Inf",
     "legendFormat": "{{method}} {{route}}"
    }
   ]
  },
  {
   "title": "Scheduler Queue",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 31 },
   "targets": [
    {
     "expr": "alert_count_in_the_execution_queue{app=~\"$app\",instance=~\"$instance\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Internal Requests Latency",
   "type": "barchart",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "((rate(internal_request_duration_seconds_sum{app=~\"$app\"}[$__rate_interval])\n/\nrate(internal_request_duration_seconds_count{app=~\"$app\"}[$__rate_interval])) > 0) != Inf",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Processes", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 40 } },
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "irate(process_cpu_user_seconds_total{instance=~\"$instance\", app=~\"$app\"}[$__rate_interval]) * 100",
     "legendFormat": "{{app}} User CPU on {{instance}}"
    },
    {
     "expr": "irate(process_cpu_system_seconds_total{instance=~\"$instance\", app=~\"$app\"}[$__rate_interval]) * 100",
     "legendFormat": "{{app}} Sys CPU on {{instance}}"
    }
   ]
  },
  {
   "title": "Event Loop Lag",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "nodejs_eventloop_lag_seconds{instance=~\"$instance\", app=~\"$app\"}",
     "legendFormat": "{{app}} on {{instance}}"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 52 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "process_resident_memory_bytes{instance=~\"$instance\", app=~\"$app\"}",
     "legendFormat": "{{app}} Process Memory on {{instance}}"
    },
    {
     "expr": "nodejs_heap_size_total_bytes{instance=~\"$instance\", app=~\"$app\"}",
     "legendFormat": "{{app}} Heap Total on {{instance}}"
    },
    {
     "expr": "nodejs_heap_size_used_bytes{instance=~\"$instance\", app=~\"$app\"}",
     "legendFormat": "{{app}} Heap Used - {{instance}}"
    },
    {
     "expr": "nodejs_external_memory_bytes{instance=~\"$instance\", app=~\"$app\"}",
     "legendFormat": "{{app}} External Memory on {{instance}}"
    }
   ]
  },
  {
   "title": "Active Handlers/Requests Total",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 52 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "nodejs_active_handles_total{instance=~\"$instance\", app=~\"$app\"}",
     "legendFormat": "{{app}} Active Handler on {{instance}}"
    },
    {
     "expr": "nodejs_active_requests_total{instance=~\"$instance\", app=~\"$app\"}",
     "legendFormat": "{{app}} Active Request on {{instance}}"
    }
   ]
  }
 ]
}