{
 "title": "Business Engine Logs",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "engine",
    "label": "Business Engine",
    "query": {}
   },
   { "name": "levels", "label": "Levels", "query": "error, warn, log, debug" }
  ]
 },
 "panels": [
  {
   "title": "Server API",
   "type": "logs",
   "gridPos": { "h": 31, "w": 8, "x": 0, "y": 0 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{container_name=~\"$engine\"} | json | context =~ `\\[server\\].+` | level =~ `$levels` | line_format `{{.container_name}} [{{.level}}] {{.context}} {{.message}}`"
    }
   ]
  },
  {
   "title": "Scheduler Service",
   "type": "logs",
   "gridPos": { "h": 31, "w": 8, "x": 8, "y": 0 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{container_name=~\"$engine\"} | json | context =~ `\\[scheduler\\].+` | level =~ `$levels` | line_format `{{.container_name}} [{{.level}}] {{.context}} {{.message}}`"
    }
   ]
  },
  {
   "title": "Renderer Microservice",
   "type": "logs",
   "gridPos": { "h": 31, "w": 8, "x": 16, "y": 0 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{container_name=~\"$engine\"} | json | context =~ `\\[renderer\\].+` | level =~ `$levels` | line_format `{{.container_name}} [{{.level}}] {{.context}} {{.message}}`"
    }
   ]
  }
 ]
}