{
 "title": "Grafana Metrics",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "instance",
    "label": "instance",
    "query": {
     "query": "label_values(grafana_build_info,instance)"
    }
   },
   {
    "name": "job",
    "label": "Job",
    "query": {
     "query": "label_values(grafana_build_info{instance=~\"$instance\"},job)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "API, Web, Proxy Requests",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by(instance) (irate(grafana_api_response_status_total{instance=~\"$instance\", job=~\"$job\"}[$__rate_interval]))",
     "legendFormat": "{{instance}} API"
    },
    {
     "expr": "sum by(instance) (irate(grafana_proxy_response_status_total{instance=~\"$instance\",job=~\"$job\"}[$__rate_interval]))",
     "legendFormat": "{{instance}} Proxy"
    },
    {
     "expr": "sum by(instance) (irate(grafana_page_response_status_total{instance=~\"$instance\",job=~\"$job\"}[$__rate_interval]))",
     "legendFormat": "{{instance}} Web"
    }
   ]
  },
  {
   "title": "HTTP Requests",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "avg by(handler, instance) (rate(grafana_http_request_duration_seconds_count{instance=~\"$instance\", job=~\"$job\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Dashboard Get",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "rate(grafana_api_dashboard_get_milliseconds_sum{instance=~\"$instance\",job=~\"$job\"}[$__rate_interval]) / rate(grafana_api_dashboard_get_milliseconds_count{instance=~\"$instance\",job=~\"$job\"}[$__rate_interval])",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "Dashboard Search",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "rate(grafana_api_dashboard_search_milliseconds_sum{instance=~\"$instance\",job=~\"$job\"}[$__rate_interval]) / \nrate(grafana_api_dashboard_search_milliseconds_count{instance=~\"$instance\",job=~\"$job\"}[$__rate_interval])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  { "title": "Processes", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 21 } },
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "irate(grafana_process_cpu_seconds_total{instance=~\"$instance\",job=~\"$job\"}[$__rate_interval]) * 100",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "In Flight HTTP Requests",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 22 },
   "targets": [
    {
     "expr": "grafana_http_request_in_flight{instance=~\"$instance\", job=~\"$job\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "rate(grafana_process_resident_memory_bytes{instance=~\"$instance\",job=~\"$job\"}[$__rate_interval])",
     "legendFormat": "{{instance}} Resident"
    },
    {
     "expr": "rate(grafana_process_virtual_memory_bytes{instance=~\"$instance\",job=~\"$job\"}[$__rate_interval])",
     "legendFormat": "{{instance}} Virtual"
    }
   ]
  },
  {
   "title": "Open File Descriptors",
   "type": "timeseries",
   "description": "Number of open file descriptors",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "grafana_process_open_fds{instance=~\"$instance\",job=~\"$job\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  }
 ]
}